### ISSUE TITLE
@InjectFromComponent throwing NPE

### ISSUE THREAD

**Issue by nealsanche** [fabioCollini/DaggerMock#16]
I can't seem to get the `@InjectFromComponent` annotation to work. I get the following error:

```
java.lang.NullPointerException
at com.google.dexmaker.mockito.DexmakerMockMaker.getInvocationHandlerAdapter(DexmakerMockMaker.java:80)
at com.google.dexmaker.mockito.DexmakerMockMaker.getHandler(DexmakerMockMaker.java:75)
at org.mockito.internal.util.MockUtil.isMockitoMock(MockUtil.java:74)
at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:66)
at org.mockito.internal.configuration.injection.scanner.MockScanner.isMockOrSpy(MockScanner.java:86)
at org.mockito.internal.configuration.injection.scanner.MockScanner.preparedMock(MockScanner.java:72)
at org.mockito.internal.configuration.injection.scanner.MockScanner.scan(MockScanner.java:61)
at org.mockito.internal.configuration.injection.scanner.MockScanner.addPreparedMocks(MockScanner.java:47)
at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:96)
at org.mockito.internal.configuration.InjectingAnnotationEngine.processInjectMocks(InjectingAnnotationEngine.java:62)
at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:56)
at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
at it.cosenonjaviste.daggermock.DaggerMockRule$1.evaluate(DaggerMockRule.java:80)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1729)
```

I have a Component that has two modules in it. A NetworkModule and a UserModule. These are purely for separating the different parts, as most of the injected stuff are singletons anyway.

I'm not sure how to help you with diagnosing this. Let me know and I'll try and get you whatever you need.

**Comment by plastiv** [comment]
It looks like dexmaker issue, which is fixed here: https://github.com/crittercism/dexmaker/commit/17cc9ccdd52a8b27793ec12f3cebb93ddf469af4 but was never released (project is kinda abandoned for now)

Try with
```
repositories {
    jcenter()
    maven { url "https://jitpack.io" } // delete after dexmaker 1.5 released
}
ext {
    dexmakerVersion = 'f8e7c23e4172af8767758c99c9165dd2bd4f0e7f' // replace with 1.5 when released
}
dependencies {
    // dexmaker is required to run mockito at android device tests
    androidTestCompile "com.github.crittercism.dexmaker:dexmaker-parent:$dexmakerVersion"
    androidTestCompile "com.github.crittercism.dexmaker:dexmaker-mockito:$dexmakerVersion"
    androidTestCompile "com.github.crittercism.dexmaker:dexmaker-dx:$dexmakerVersion"
    androidTestCompile "com.github.crittercism.dexmaker:dexmaker:$dexmakerVersion"
}
```

I also had issues with mockito v2 and had to use `1.10.19` for now.

**Comment by nealsanche** [comment]
Yeah, that looks like the issue alright. Thanks for that! I gave the dependencies a massage, including the version you specified above, and the error is gone.

**Comment by rpattabi** [comment]
Just noticed that dexmaker has new releases including the one that works with latest mockito.

**Comment by plastiv** [comment]
@rpattabi also, if you migrated to mockito v2 (2.6.2) they have `android` artifact which replaces `dexmaker` (I assume). At least it works without `dexmaker` now.

**Comment by rpattabi** [comment]
@plastiv Good to see android support is directly coming from mockito team. Replacing dexmaker with mockito-android works fine for me. Thanks.

```
ext.mockitoVersion = '2.6.3'
testCompile "org.mockito:mockito-core:$mockitoVersion"
androidTestCompile "org.mockito:mockito-android:$mockitoVersion"
```

There is hope now that mockito-android is expected to evolve with mockito.
