### ISSUE TITLE
Support Component dependency with dependency.

### ISSUE THREAD

**Issue by ChrisZou** [fabioCollini/DaggerMock#17]
Hi, I have a `AppComponent`, which depends on `ApiComponent`, and `ApiComponent` depends on `CommonComponent`. How can I use DaggerMock for `AppComponent`?
I know I can use `addComponentDependency(ApiComponent.class, new ApiModule())` to add a ApiComponent. 

```
public class DaggerRule extends DaggerMockRule<AppComponent> {
    public DaggerRule() {
        super(AppComponent.class, new AppModule());
        addComponentDependency(ApiComponent.class, new ApiModule());
        set(new DaggerMockRule.ComponentSetter<AppComponent>() {
            @Override
            public void setComponent(AppComponent component) {
                ComponentHolder.setAppComponent(component);
            }
        });
    }
}
```

But it seems not enough. The following error message occurs:

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at it.cosenonjaviste.daggermock.DaggerMockRule.initComponentDependencies(DaggerMockRule.java:140)
	at it.cosenonjaviste.daggermock.DaggerMockRule.access$300(DaggerMockRule.java:35)
	at it.cosenonjaviste.daggermock.DaggerMockRule$3.evaluate(DaggerMockRule.java:91)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:16)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at it.cosenonjaviste.daggermock.DaggerMockRule.buildComponent(DaggerMockRule.java:148)
	at it.cosenonjaviste.daggermock.DaggerMockRule.initComponentDependencies(DaggerMockRule.java:134)
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at it.cosenonjaviste.daggermock.DaggerMockRule.buildComponent(DaggerMockRule.java:146)
	... 23 more
Caused by: java.lang.IllegalStateException: commonComponent must be set
	at com.my_package.name.DaggerApiComponent$Builder.build(DaggerApiComponent.java:230)
	... 28 more
```

And if I call `addComponentDependency()` for both `ApiComponent` and `CommonComponent`:

```
public class DaggerRule extends DaggerMockRule<AppComponent> {
    public DaggerRule() {
        super(AppComponent.class, new AppModule());
        addComponentDependency(CommonComponent.class, new CommonModule());
        addComponentDependency(ApiComponent.class, new ApiModule());
        set(new DaggerMockRule.ComponentSetter<AppComponent>() {
            @Override
            public void setComponent(AppComponent component) {
                ComponentHolder.setAppComponent(component);
            }
        });
    }
}
```

Then the following error occurs:

```
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.mogujie.mgjpaysdk.dagger.DaggerAppComponent$Builder.commonComponent(com.mogujie.mgjpfcommon.dagger.CommonComponent)

	at it.cosenonjaviste.daggermock.DaggerMockRule.initComponentDependencies(DaggerMockRule.java:140)
	at it.cosenonjaviste.daggermock.DaggerMockRule.access$300(DaggerMockRule.java:35)
	at it.cosenonjaviste.daggermock.DaggerMockRule$3.evaluate(DaggerMockRule.java:91)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:16)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NoSuchMethodException: com.mogujie.mgjpaysdk.dagger.DaggerAppComponent$Builder.commonComponent(com.mogujie.mgjpfcommon.dagger.CommonComponent)
	at java.lang.Class.getMethod(Class.java:1786)
	at it.cosenonjaviste.daggermock.DaggerMockRule.getComponentSetterMethod(DaggerMockRule.java:173)
	at it.cosenonjaviste.daggermock.DaggerMockRule.initComponentDependencies(DaggerMockRule.java:135)
	... 22 more
```

How can I get DaggerMock to work with `AppComponent`?

**Comment by fabioCollini** [comment]
Hi,
nested dependency are not supported in current version and it's not easy to manage them :(
I'll take a look in the next days to find the simplest way to implement this feature.
Thanks for your report

**Comment by fabioCollini** [comment]
Hi,
I have implemented support for nested component, can you please try it and give some feedbacks? You can use the new release using version aff7619314. An example is available here: https://github.com/fabioCollini/DaggerMock/blob/master/lib/src/test/java/it/cosenonjaviste/daggermock/nesteddependency/ComponentNestedDependencyTest.java there is an new overload of the method addComponentDependency with two components parameters (the parent and the child component).

**Comment by ChrisZou** [comment]
Hi @fabioCollini Thank you for the support. How can I try the specific version `aff7619`?

**Comment by fabioCollini** [comment]
Hi, you can just use the commit hash as version. More info are available here: https://jitpack.io/#fabioCollini/DaggerMock/aff7619314

Thanks for your help!

**Comment by ChrisZou** [comment]
Hi @fabioCollini. I tried it and it works very well. Thank you for the great work, it really simplifies testing!
