### ISSUE TITLE
AndroidManifest.xml not found or not a file

### ISSUE THREAD

**Issue by prathameshtal** [fabioCollini/DaggerMock#49]
I am facing following error while running unit test cases from "app" folder

`"/Applications/Android` Studio.app/Contents/jre/jdk/Contents/Home/bin/java" -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/Android Studio.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/Android Studio.app/Contents/lib/idea_rt.jar:/Applications/Android Studio.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/prathamesht/Library/Android/sdk/platforms/android-24/data/res:/Users/prathamesht/Documents/Android/SampleProjects/testcases/DaggerMock-master/app/build/intermediates/classes/test/debug:/Users/prathamesht/Documents/Android/SampleProjects/testcases/DaggerMock-master/app/build/intermediates/classes/debug:/Users/prathamesht/.android/build-cache/6c5826a4f266aec596ed61605d2e3c24a8b41fed/output/jars/classes.jar:/Users/prathamesht/.android/build-cache/6c5826a4f266aec596ed61605d2e3c24a8b41fed/output/res:/Users/prathamesht/.android/build-cache/db95f7754e3ce1b446ce07255b56e0a965082dfd/output/res:/Users/prathamesht/.android/build-cache/db95f7754e3ce1b446ce07255b56e0a965082dfd/output/jars/libs/internal_impl-24.2.1.jar:/Users/prathamesht/.android/build-cache/db95f7754e3ce1b446ce07255b56e0a965082dfd/output/jars/classes.jar:/Users/prathamesht/.android/build-cache/f96f74823c4ae4db59714f21079adea913241880/output/jars/classes.jar:/Users/prathamesht/.android/build-cache/f96f74823c4ae4db59714f21079adea913241880/output/jars/libs/internal_impl-24.2.1.jar:/Users/prathamesht/.android/build-cache/f96f74823c4ae4db59714f21079adea913241880/output/res:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.6.11/200d9c012befccd211ff91082a151257b1dc084/byte-buddy-agent-1.6.11.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.6.11/8a8f9409e27f1d62c909c7eef2aa7b3a580b4901/byte-buddy-1.6.11.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/5.0.1/7b7147a390a93a14d2edfdcf3f7b0e87a0939c3e/asm-commons-5.0.1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/5.0.1/2fd56467a018aafe6ec6a73ccba520be4a7e1565/asm-5.0.1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.robolectric/shadows-core/3.0/9dfa881bfd1796afa28204ef1a5ed7e3de992612/shadows-core-3.0.jar:/Users/prathamesht/.android/build-cache/da84dcc6de5513edd8a274efcbf87c77a65996b5/output/res:/Users/prathamesht/.android/build-cache/da84dcc6de5513edd8a274efcbf87c77a65996b5/output/jars/libs/internal_impl-24.2.1.jar:/Users/prathamesht/.android/build-cache/da84dcc6de5513edd8a274efcbf87c77a65996b5/output/jars/classes.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/53.1/786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f/icu4j-53.1.jar:/Users/prathamesht/.android/build-cache/0e26a92a23acfef1131372d986bd91c1a97d947e/output/res:/Users/prathamesht/.android/build-cache/0e26a92a23acfef1131372d986bd91c1a97d947e/output/jars/classes.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/2.8.8/749da28f1215d8e72e8dc9658399ff26c259959e/mockito-core-2.8.8.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric-resources/3.0/1ab609054aab67cd13a434567467f4b4774f2465/robolectric-resources-3.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.almworks.sqlite4java/sqlite4java/0.282/745a7e2f35fdbe6336922e0d492c979dbbfa74fb/sqlite4java-0.282.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/5.0.1/1b1e6e9d869acd704056d0a4223071a511c619e6/asm-tree-5.0.1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger/2.7/f60e4926b5f05a62ff73e73b6eb3a856cdc74ddb/dagger-2.7.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger-producers/2.7/109b30d9c44c037e3bee87e85564fd604a7d432f/dagger-producers-2.7.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.assertj/assertj-core/2.5.0/fcd21db4c5f33e5dcac69bf1816415fe0647582f/assertj-core-2.5.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric/3.0/f888cea3bc1a24110e315eb9827ab593610ea62f/robolectric-3.0.jar:/Users/prathamesht/.android/build-cache/b2fdfe5caa0ed8e80718da33ba69dc1a8295a359/output/jars/classes.jar:/Users/prathamesht/.android/build-cache/b2fdfe5caa0ed8e80718da33ba69dc1a8295a359/output/res:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-ant-tasks/2.1.3/b09be554228d66d208e5fef5266844aacf443abc/maven-ant-tasks-2.1.3.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant/1.8.0/7b456ca6b93900f96e58cc8371f03d90a9c1c8d1/ant-1.8.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.google.android.apps.common.testing.accessibility.framework/accessibility-test-framework/1.0/28162aae36f8ba5903adadfb570313e1f1be852e/accessibility-test-framework-1.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant-launcher/1.8.0/8b53ba16fa62fb1034da8f1de200ddc407c8381/ant-launcher-1.8.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger-compiler/2.7/65aa7daec6dd64bf4f3208b268c38c6a4fb2b849/dagger-compiler-2.7.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/5.0.1/7c8caddfbd0b2d7b844f8fcc75175b9cb9cf4724/asm-util-5.0.1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk16/1.46/ce091790943599535cbb4de8ede84535b0c1260c/bcprov-jdk16-1.46.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/javax.annotation/jsr250-api/1.0/5025422767732a1ab45d93abfea846513d742dcf/jsr250-api-1.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/2.5/612ecb799912ccf77cba9b3ed8c813da086076e9/objenesis-2.5.jar:/Users/prathamesht/.android/build-cache/f14614e8600d8963ebfca708df5ef63f3f66616d/output/jars/classes.jar:/Users/prathamesht/.android/build-cache/f14614e8600d8963ebfca708df5ef63f3f66616d/output/res:/Users/prathamesht/.android/build-cache/f14614e8600d8963ebfca708df5ef63f3f66616d/output/jars/libs/internal_impl-24.2.1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar:/Users/prathamesht/.android/build-cache/5a4973c6054e0a5c45d98cb9a404ebe7c03761a0/output/res:/Users/prathamesht/.android/build-cache/5a4973c6054e0a5c45d98cb9a404ebe7c03761a0/output/jars/classes.jar:/Users/prathamesht/.android/build-cache/ad264622e68628c4cd6a4be3acc9ef8c6b497f73/output/jars/classes.jar:/Users/prathamesht/.android/build-cache/ad264622e68628c4cd6a4be3acc9ef8c6b497f73/output/res:/Users/prathamesht/.android/build-cache/ad264622e68628c4cd6a4be3acc9ef8c6b497f73/output/jars/libs/internal_impl-24.2.1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric-annotations/3.0/2a6cfc072d7680694c1ff893c5dc8fec33163110/robolectric-annotations-3.0.jar:/Users/prathamesht/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/24.2.0/support-annotations-24.2.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric-utils/3.0/4bcecd8115fe7296088bb1636e6cbd7ae8927392/robolectric-utils-3.0.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/5.0.1/e286fbee48efacb4e7c175f7948d9d8b2ab52352/asm-analysis-5.0.1.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/com.ximpleware/vtd-xml/2.11/ee5bcf62c1acf76434ee9f1c67a840bafef72a6d/vtd-xml-2.11.jar:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/prathamesht/Documents/Android/SampleProjects/testcases/DaggerMock-master/lib/build/classes/java/test:/Users/prathamesht/Documents/Android/SampleProjects/testcases/DaggerMock-master/lib/build/classes/java/main:/Users/prathamesht/.gradle/caches/modules-2/files-2.1/org.glassfish/javax.annotation/10.0-b28/30eb3b3cc9cb0863a4edaea5a7575f8ace1b96ba/javax.annotation-10.0-b28.jar:/Users/prathamesht/Documents/Android/SampleProjects/testcases/DaggerMock-master/app/build/intermediates/sourceFolderJavaResources/test/debug:/Users/prathamesht/Documents/Android/SampleProjects/testcases/DaggerMock-master/app/build/intermediates/sourceFolderJavaResources/debug:/Users/prathamesht/Documents/Android/SampleProjects/testcases/DaggerMock-master/build/generated/mockable-android-24.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 it.cosenonjaviste.daggermock.demo.robolectric.MainActivityTest
java.lang.RuntimeException: build/intermediates/bundles/debug/AndroidManifest.xml not found or not a file; it should point to your project's AndroidManifest.xml
	at org.robolectric.manifest.AndroidManifest.validate(AndroidManifest.java:121)
	at org.robolectric.manifest.AndroidManifest.getResourcePath(AndroidManifest.java:469)
	at org.robolectric.manifest.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:475)
	at org.robolectric.RobolectricTestRunner.createAppResourceLoader(RobolectricTestRunner.java:491)
	at org.robolectric.RobolectricTestRunner.getAppResourceLoader(RobolectricTestRunner.java:483)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:73)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

java.lang.RuntimeException: java.lang.RuntimeException: build/intermediates/bundles/debug/AndroidManifest.xml not found or not a file; it should point to your project's AndroidManifest.xml

	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:244)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: build/intermediates/bundles/debug/AndroidManifest.xml not found or not a file; it should point to your project's AndroidManifest.xml
	at org.robolectric.manifest.AndroidManifest.validate(AndroidManifest.java:121)
	at org.robolectric.manifest.AndroidManifest.getResourcePath(AndroidManifest.java:469)
	at org.robolectric.manifest.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:475)
	at org.robolectric.RobolectricTestRunner.createAppResourceLoader(RobolectricTestRunner.java:491)
	at org.robolectric.RobolectricTestRunner.getAppResourceLoader(RobolectricTestRunner.java:483)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:73)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	... 19 more

Process finished with exit code 255`

**Comment by fabioCollini** [comment]
It seems related to Robolectric, I think you need to configure the working directory in the test run configuration. More info available here in the section "Note for Linux and Mac Users": http://robolectric.org/getting-started/
