### ISSUE TITLE
You must define overridden objects using a @provides annotated method instead of using @Inject annotation

### ISSUE THREAD

**Issue by salan1** [fabioCollini/DaggerMock#98]
Hi,
I'm having issues getting dagger mock working with my DI current setup. 

`Error while trying to override objects:
    com.example.end.domain.interactors.GetProductsUseCase
    You must define overridden objects using a @Provides annotated method instead of using @Inject annotation`

This occurs when trying to override GetProductsUseCase which uses a @Provides annotation in it's module. My current setup:

[https://github.com/salan1/End/tree/master/app/src/main/java/com/example/end/di](url)

Full Error:
`E/TestRunner: java.lang.RuntimeException: Error while trying to override objects:
    com.example.end.domain.interactors.GetProductsUseCase
    You must define overridden objects using a @Provides annotated method instead of using @Inject annotation
        at it.cosenonjaviste.daggermock.ErrorsFormatter.throwExceptionOnErrors(ErrorsFormatter.java:42)
        at it.cosenonjaviste.daggermock.OverriddenObjectsMap.checkOverriddenInjectAnnotatedClass(OverriddenObjectsMap.java:77)
        at it.cosenonjaviste.daggermock.DaggerMockRule.setupComponent(DaggerMockRule.java:150)
        at it.cosenonjaviste.daggermock.DaggerMockRule.access$000(DaggerMockRule.java:36)
        at it.cosenonjaviste.daggermock.DaggerMockRule$1.evaluate(DaggerMockRule.java:136)
        at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
`

Thank you in advance

**Comment by fabioCollini** [comment]
Hi, looking at your project it seems that you using Dagger Android and that you are trying to replace `GetProductsUseCase` that is defined at the `FragmentScope`. Unfortunately using DaggerMock with Dagger Android you can replace only objects defined at the `ApplicationScope`.
In your case maybe you can move the `GetProductsUseCase` definition to `ApplicationModule` because it depends only on a Singleton.

**Comment by salan1** [comment]
OK thanks for the help. Any plans for better Dagger Android support in the future or is it just a limitation?
